### ISSUE TITLE
upstream 1.0.18

### ISSUE THREAD

**Issue by cgtx** [iusrepo/libmemcached10#1]
I'm opening this issue mostly as a note to myself, so I don't have to look this info up again in the future.

As of 2014-02-09, upstream libmemcached is at version [1.0.18](https://launchpad.net/libmemcached/1.0/1.0.18).  Our package is still at version [1.0.16](https://github.com/iuscommunity-pkg/libmemcached10/blob/97b7b7e7b1eaaeb21a0881367686ec1db0efc747/SPECS/libmemcached10.spec#L9).  Unlike most other projects, libmemcached upstream does a pretty terrible job maintaining [API compatibility](http://upstream.rosalinux.ru/versions/libmemcached.html).  We [wanted to build the IUS pecl modules for memcached](https://github.com/iuscommunity-pkg/php55u-pecl-memcached/issues/1) against [stock EL5/6 libmemcached version 0.31](http://ftp.redhat.com/redhat/linux/enterprise/6Server/en/os/SRPMS/libmemcached-0.31-1.1.el6.src.rpm), but the pecl module upstream seems to have [zero interest](https://github.com/php-memcached-dev/php-memcached/issues/146) in making it compile against this old version.

Since this package is just a [supporting package](https://iuscommunity.org/pages/IUSClientUsageGuide.html#secondary-supporting-packages) (i.e. a means to an end to get pecl-memcached for our php stacks), then it will likely just hang out in limbo, unless the pecl memcached developers decide to actually support the 0.x libmemcached series, as [their changelog states](https://github.com/php-memcached-dev/php-memcached/blob/def716a80f1be732b5dad1c13d3023248db64881/ChangeLog#L5).

**Comment by gotyaoi** [comment]
I'd like to raise the possibility of this version of the package making it into IUS. We've recently been debugging a 5 second hang when using php56u-pecl-memcached that we traced into libmemcached10-1.0.16. Replacing that with a manually compiled libmemcached 1.0.18 resolved the issue.

Additionally, the github readme of pecl-memcached states that:

>libmemcached version 1.0.18 or higher is recommended for best performance and compatibility with memcached servers.

So if php56u-pecl-memcached was ever to be updated, an update to libmemcached would probably be required as well.

**Comment by b-harper** [comment]
@gotyaoi, thanks for taking the time to reach out regarding your concerns.  Some additional information regarding libmemcached made into into the [php70u-pecl-memcached new package request issue][0] but that information never made it back into this issue.

@carlwgeorge reached out the pecl memcached developers to get clarification about that statement in [this issue][1].  We did not get the clarification we were looking for and only further complicates how we should proceed.  Given the [current life cycle status of EL6][2], I am hesitant to make changes that will keep people from migrating off EL6.  


[0]: https://github.com/iuscommunity/wishlist/issues/34#issuecomment-302728082
[1]: https://github.com/php-memcached-dev/php-memcached/issues/310#issuecomment-278649066
[2]: https://github.com/iuscommunity/announce/issues/5

**Comment by gotyaoi** [comment]
Hah, in fact, reading it, https://github.com/php-memcached-dev/php-memcached/issues/310 describes the exact issue we're having, with memcached binary touch. Small world. Not with lazy_write though, as that option wasn't available until PHP 7.0.0.

Regarding libmemcached being abandonware, yes, that definitely appears to be the case. However, as long as pecl-memcached is built on top of it, we appear to be stuck with it, so maybe having the last released version of said abandonware would be better.

Regarding the EL6 policy, I think this would qualify more as a bug fix than a new thing. And we do intend to migrate to EL7, but it's quite the process and the machines this is affecting aren't at the top of the list.

Additionally, anyone running PHP 5.6 from IUS with pecl-memcached on EL7 will also be running into this problem, as the RH supplied version of libmemcached is 1.0.16. There were workarounds introduced in newer versions of pecl-memcached which disable the binary protocol if it detects an older version of libmemcached, but then there are certain operations which are only possible with the binary protocol.

**Comment by b-harper** [comment]
My hesitation comes with much thought and deliberation.  @carlwgeorge and myself have had numerous lengthy conversations on how to handle libmemcached and the memcached pecl module.  We have covered every angle and there is no good answer on how to proceed.  The fact that the memcached pecl module is still going even though the client library is dead, makes this even trickier. If it were up to just me, I would have looked to sunset the memcached packages a long time ago.  But, to your point, people are using these packages and migrations are easier said than done. 

IUS does not have the resources of Red Hat and thus we relay on the upstream projects for security patches.  I think it would be irresponsible for us to release a new libmemcached package on EL7.  EL6 is a different story as we started packaging it before it was abandoned.  Given that Red Hat does not provide updates for bug fixes, performance or new features, but only the most critical security patches for EL6, I think it is a tough ask for a third party repository to do what Red Hat won't do.

Personally, I only have a single PHP application in 'production', a personal Nextcloud instance. When I moved from PHP 5.6 to PHP 7, I switched from memcached to redis for my caching needs.  At that time, there was not a version of the memcached module that supported PHP 7.  From my limited prescriptive, it seems that people are moving away from memcached in favor of caching solutions with a healthier development communities.

**Comment by gotyaoi** [comment]
I understand your position, and as it may be just us needing this, we can probably use the IUS SPEC file for 1.0.16 to build a 1.0.18. Thank you for your consideration.

**Comment by carlwgeorge** [comment]
Nothing has changed with the upstream libmemcached project since I opened this issue.  IUS intends to continue building our php*-pecl-memcached EL7 packages against stock libmemcached-1.0.16.  We don't intend to build libmemcached10 for EL7, or update the EL6 package newer than the stock EL7 package version.  As this issue is at a standstill I'm going to close it.
